version: '3.3'
services:
  api:
    container_name: "operations-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    expose:
      - 8082

volumes:
  postgres-data: