services:
  api:
    container_name: "operations-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - 8081
    env_file:
      - .env

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  asset_service_dev:
    container_name: "asset_service_dev"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite_dev:
      image: mcr.microsoft.com/azure-storage/azurite
      container_name: "azurite_dev"
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
      volumes:
        - blob:/workspace


volumes:
  postgres-data:
  blob:
    external: false
