services:
  snippet-operations:
    container_name: "snippet-operations"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_OPERATIONS_HOST: ${POSTGRES_OPERATIONS_HOST}
      POSTGRES_OPERATIONS_PORT: ${POSTGRES_OPERATIONS_PORT}
      BUCKET_URL: ${BUCKET_URL}
      PERMISSIONS_URL: ${PERMISSIONS_URL}
      RUNNER_URL: ${RUNNER_URL}
      NEW_RELIC_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NEW_RELIC_AGENT_ENABLED: ${NEW_RELIC_AGENT_ENABLED}
    depends_on:
        - asset-service
        - postgres-operations

  postgres-operations:
    container_name: "postgres-operations"
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-operations-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  asset-service:
    container_name: "asset-service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: ${NEW_RELIC_AGENT_ENABLED}

  azurite:
      container_name: "azurite"
      image: mcr.microsoft.com/azure-storage/azurite
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
      volumes:
        - blob:/workspace

volumes:
  postgres-operations-data:
  blob:
    external: false
