version: '3.3'
services:
  api:
    container_name: "operations-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    image: ghcr.io/austral-ingsis/snippet-asset-service:main.7
    expose:
      - 8082

  api2:
    container_name: "asset_service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "azurite"
    hostname: azurite
    restart: always
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - blob:/workspace


volumes:
  postgres-data:
  blob:
      external: false