services:
  operations-api:
    container_name: "operations-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      BUCKET_URL: ${BUCKET_URL}
      POSTGRES_OPERATIONS_PORT: ${POSTGRES_OPERATIONS_PORT}
      PERMISSIONS_URL: ${PERMISSIONS_URL}
    depends_on:
        - asset_service_dev
        - postgres

  postgres:
    container_name: "postgres"
    image: postgres:alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  asset-service:
    container_name: "asset-service"
    image: ghcr.io/austral-ingsis/snippet-asset-service:latest
    ports:
      - "8080:8080"
    environment:
      AZURE_HOST: "http://azurite"
      NEW_RELIC_AGENT_ENABLED: false

  azurite:
      container_name: "azurite"
      image: mcr.microsoft.com/azure-storage/azurite
      hostname: azurite
      restart: always
      ports:
        - "10000:10000"
        - "10001:10001"
        - "10002:10002"
      volumes:
        - blob:/workspace

volumes:
  postgres-data:
  blob:
    external: false
