services:
  api:
    container_name: "operations-api"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - 8081

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  postgres-data:
main
